export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const CART_ROUTE = '/cart'
export const SHOP_ROUTE = '/'
export const VINYL_ROUTE = '/vinyl'
export const HOME_ROUTE = '/home'